# tests/test_r12_generator.py
"""
R12 Email Pattern Generator Tests

Tests email permutation generation from names.

NOTE: The generator produces these patterns:
- john.doe@domain.com (first.last)
- jdoe@domain.com (flast - first initial + last)
- johnd@domain.com (firstl - first + last initial)
- john@domain.com (first)
- johndoe@domain.com (firstlast)
- john_doe@domain.com (first_last)

The `doej@` pattern (lastf - last + first initial) is NOT generated.
"""

from __future__ import annotations

from src.generate.permutations import (
    generate_permutations,
    infer_domain_pattern,
    normalize_name_parts,
)


def test_basic_patterns():
    """Test that basic email patterns are generated."""
    emails = generate_permutations("John", "Doe", "example.com")

    # These patterns ARE generated by the current implementation
    assert "john.doe@example.com" in emails  # first.last
    assert "jdoe@example.com" in emails  # flast (first initial + last)

    # NOTE: doej@ (lastf) is NOT generated by the current implementation
    # The generator produces: first.last, flast, firstl, first, firstlast, first_last

    # At least these core patterns should be present
    for pattern in ("john.doe@example.com", "jdoe@example.com", "john@example.com"):
        assert pattern in emails, f"Expected {pattern} in generated emails"


def test_role_aliases_blocked():
    """Ensure role aliases are filtered from permutations."""
    emails = generate_permutations("Info", "", "example.com")
    assert all(not e.startswith("info@") for e in emails)


def test_accented_names_normalize():
    """Test that accented characters are normalized to ASCII."""
    result = normalize_name_parts("José", "Gonçalves")
    # Should normalize accented characters
    assert result[0] == "jose"  # first name normalized
    assert result[1] == "goncalves"  # last name normalized
    assert result[2] == "j"  # first initial
    assert result[3] == "g"  # last initial


def test_pattern_inference_limits_candidates():
    """Test that inferred patterns limit generated candidates."""
    # Use non-placeholder names (avoid doe)
    published = ["alice.smith@example.com", "bob.wilson@example.com"]
    only = infer_domain_pattern(published, "Carol", "Martinez")
    emails = generate_permutations(
        "Carol",
        "Martinez",
        "example.com",
        only_pattern=only,
    )

    # When pattern is inferred from existing emails (first.last), only that pattern is generated
    assert emails == {"carol.martinez@example.com"}
