# scripts/migrate_o06_mx_behavior.py
from __future__ import annotations

import argparse
import os
import sys

from src.db import get_conn

UTC_NOW_TEXT_SQL = "to_char((now() at time zone 'utc'), 'YYYY-MM-DD HH24:MI:SS')"

DDL = f"""
CREATE TABLE IF NOT EXISTS mx_probe_stats (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  mx_host    TEXT NOT NULL,
  ts         TEXT NOT NULL DEFAULT ({UTC_NOW_TEXT_SQL}),
  code       INTEGER,               -- SMTP RCPT code or NULL on transport error
  category   TEXT,                  -- 'accept' | 'hard_fail' | 'temp_fail' | 'unknown'
  error_kind TEXT,                  -- 'timeout'|'disconnected'|'smtp_response'|... or NULL
  elapsed_ms INTEGER                -- probe latency in ms
);

CREATE INDEX IF NOT EXISTS idx_mx_probe_host_ts ON mx_probe_stats(mx_host, ts);
""".strip()


def apply_dsn_override(dsn: str | None) -> None:
    if not dsn:
        return
    os.environ["DATABASE_URL"] = dsn


def main() -> None:
    ap = argparse.ArgumentParser(
        description="O06 migration: ensure mx_probe_stats exists (PostgreSQL)"
    )
    ap.add_argument(
        "--dsn",
        "--db",
        dest="dsn",
        default=None,
        help="Postgres DSN/URL (optional; overrides DATABASE_URL for this run).",
    )
    args = ap.parse_args()
    apply_dsn_override(args.dsn)

    conn = get_conn()
    try:
        cur = conn.cursor()
        try:
            # Execute statements individually for drivers that disallow multi-statement execute().
            for stmt in DDL.split(";"):
                s = stmt.strip()
                if s:
                    cur.execute(s)
        finally:
            try:
                cur.close()
            except Exception:
                pass
        conn.commit()
    except Exception:
        try:
            conn.rollback()
        except Exception:
            pass
        raise
    finally:
        try:
            conn.close()
        except Exception:
            pass

    print("✔ O06 migration completed (mx_probe_stats ensured).")


if __name__ == "__main__":
    try:
        main()
    except Exception as e:
        print(f"ERROR: {e}", file=sys.stderr)
        sys.exit(1)
